#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
src/kmean.py

Version
-------
v8_auto_count_percentage

Utilities for KMeans-based traffic-node candidate detection from a route
hit-density map.

The important idea is:
    candidate node = raw model node that is not DB/DK/FLZ/RA and is preferably
    crossed by many already-planned routes within HIT_BUFFER_M.

Major nodes are selected from high route-hit-density areas.
Minor nodes are selected from a broader pool to improve regional coverage.

Diagnostic figures generated by v8_auto_count_percentage:
    figures/00_trafic_density.png
        Mesh-style traffic-density surface from route hit-counts.
    figures/01_route_hit_density.png
        Point-based node hit-density map.
    figures/02_kmean_major_minor_candidates.png
        KMeans major/minor candidate map.
    figures/03_hit_count_histogram.png
        Histogram of route-hit counts.


IMPORTANT COPY NOTE
-------------------
This is a versioned drop-in replacement for src/kmean.py.
Copy this whole file to src/kmean.py if your editor/cache does not show the
updated file. It contains both:
    1) strict route geometry reading/validation, and
    2) figures/00_trafic_density.png mesh traffic-density plotting.

Route geometry fix in v11_candidate_clearance_shift:
    The primary reader now uses output/02_thetastar_master_plan/all_route_edges_v4.csv.
    Each route is reconstructed from ordered edges:
        route_key + edge_seq + x1/y1 -> x2/y2.
    If route_key is unavailable, a new route starts whenever edge_seq resets
    back to 0 or decreases. This avoids the old wrong logic that guessed route
    polylines from generic CSV columns. Legacy CSV reading remains available as
    a fallback only when the edge file is disabled or missing.

Figure 02 candidate display update in v11_candidate_clearance_shift:
    The KMeans major and minor traffic-node candidates are controlled by params.
    Candidate labels can be turned on/off without editing this source file.
"""

from __future__ import annotations

import ast
import glob
import math
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from types import SimpleNamespace
from typing import Iterable, Sequence

import numpy as np
import pandas as pd
from scipy.spatial import cKDTree

try:
    from sklearn.cluster import KMeans
except Exception as exc:  # pragma: no cover - handled at runtime
    KMeans = None
    _SKLEARN_IMPORT_ERROR = exc
else:
    _SKLEARN_IMPORT_ERROR = None


MODULE_VERSION = "v11_candidate_clearance_shift"  # VISIBLE VERSION TAG - 2026-07-01


# ----------------------------------------------------------------------
# Parameter handling
# ----------------------------------------------------------------------


def load_params(params_file: str | Path) -> SimpleNamespace:
    """Load a Python-style .params file into a namespace."""
    params_file = Path(params_file)
    if not params_file.exists():
        raise FileNotFoundError(f"Parameter file not found: {params_file}")

    namespace: dict[str, object] = {}
    code = params_file.read_text(encoding="utf-8")
    exec(compile(code, str(params_file), "exec"), {}, namespace)

    clean = {k: v for k, v in namespace.items() if not k.startswith("__")}
    clean["PARAMS_FILE"] = str(params_file)
    return SimpleNamespace(**clean)


def pget(params: SimpleNamespace, name: str, default=None):
    return getattr(params, name, default)


# ----------------------------------------------------------------------
# Data containers
# ----------------------------------------------------------------------


@dataclass
class LoadedModel:
    df: pd.DataFrame
    x_col: str
    y_col: str
    z_col: str | None
    slowness_col: str | None
    label_col: str
    label_prefix_col: str
    xy_original: np.ndarray
    xy_metric: np.ndarray
    metric_origin_lonlat: tuple[float, float] | None
    metric_mode: str


@dataclass
class LoadedRoute:
    path: Path
    xy_original: np.ndarray
    xy_metric: np.ndarray
    n_raw_points: int
    n_dense_points: int
    hit_nodes: int
    status: str
    reason: str = ""
    route_key: str = ""
    source_kind: str = ""


# ----------------------------------------------------------------------
# Basic helpers
# ----------------------------------------------------------------------


def _as_list(value) -> list:
    if value is None:
        return []
    if isinstance(value, (list, tuple, set)):
        return list(value)
    return [value]


def _norm_col(name: str) -> str:
    return str(name).strip().lower().replace(" ", "_")


def _find_column(df: pd.DataFrame, candidates: Sequence[str]) -> str | None:
    """Find a column using case-insensitive exact matching first, then relaxed.

    This relaxed function is kept for the raw model file because model-column
    names are controlled by our own scripts. Do not use it for route geometry:
    route summary files often contain columns such as start_x/end_x/center_x,
    which must not be interpreted as route polylines.
    """
    if df is None or df.empty:
        return None
    lookup = {_norm_col(c): c for c in df.columns}
    for cand in candidates:
        key = _norm_col(cand)
        if key in lookup:
            return lookup[key]

    # relaxed partial match, useful for model columns like route_x_m or model_y_m
    norm_cols = [(_norm_col(c), c) for c in df.columns]
    for cand in candidates:
        key = _norm_col(cand)
        for norm, original in norm_cols:
            if norm == key or norm.endswith("_" + key) or norm.startswith(key + "_"):
                return original
    return None


def _find_column_exact(df: pd.DataFrame, candidates: Sequence[str]) -> str | None:
    """Find a column by case-insensitive exact normalized name only."""
    if df is None or df.empty:
        return None
    lookup = {_norm_col(c): c for c in df.columns}
    for cand in candidates:
        key = _norm_col(cand)
        if key in lookup:
            return lookup[key]
    return None


def _coerce_numeric(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce")


def _looks_like_headerless_numeric(df: pd.DataFrame) -> bool:
    if df.empty:
        return False
    try:
        numeric_cols = sum(pd.to_numeric(df.iloc[:, i], errors="coerce").notna().mean() > 0.8 for i in range(min(3, df.shape[1])))
        return numeric_cols >= 2
    except Exception:
        return False


def _read_table_flexible(path: str | Path) -> pd.DataFrame:
    """Read CSV/whitespace table with or without header."""
    path = Path(path)

    # First try header-aware read. sep=None handles comma/semicolon/tab reasonably.
    attempts = [
        dict(sep=None, engine="python", comment="#"),
        dict(sep=r"\s+", engine="python", comment="#"),
    ]

    for kwargs in attempts:
        try:
            df = pd.read_csv(path, **kwargs)
            if df.shape[1] >= 2:
                return df
        except Exception:
            pass

    # Headerless fallback.
    for kwargs in attempts:
        try:
            df = pd.read_csv(path, header=None, **kwargs)
            if df.shape[1] >= 2 and _looks_like_headerless_numeric(df):
                names = ["x", "y", "z", "slowness", "label", "label_prefix"]
                extra = [f"col_{i}" for i in range(max(0, df.shape[1] - len(names)))]
                df.columns = (names + extra)[: df.shape[1]]
                return df
        except Exception:
            pass

    raise ValueError(f"Could not read table: {path}")


def _derive_label_prefix(label: object) -> str:
    s = "" if pd.isna(label) else str(label).strip()
    if not s:
        return ""
    match = re.match(r"([A-Za-z_]+)", s)
    return match.group(1).upper() if match else s.upper()


def _is_lonlat_xy(xy: np.ndarray) -> bool:
    """Heuristic: true if coordinates look like lon/lat degrees."""
    if xy.size == 0:
        return False
    x = xy[:, 0]
    y = xy[:, 1]
    finite = np.isfinite(x) & np.isfinite(y)
    if finite.sum() == 0:
        return False
    x = x[finite]
    y = y[finite]

    # Hoa Lac-like data are around lon 105, lat 21. Keep it general enough.
    if np.nanmin(x) >= -180 and np.nanmax(x) <= 180 and np.nanmin(y) >= -90 and np.nanmax(y) <= 90:
        # If the span is degree-like, not meter-like.
        if (np.nanmax(x) - np.nanmin(x)) <= 5.0 and (np.nanmax(y) - np.nanmin(y)) <= 5.0:
            return True
    return False


def _lonlat_to_local_m(xy_lonlat: np.ndarray, origin_lonlat: tuple[float, float]) -> np.ndarray:
    """Convert lon/lat degrees to local equirectangular meters."""
    lon0, lat0 = origin_lonlat
    lat0_rad = math.radians(lat0)
    earth_r = 6371000.0
    lon = np.asarray(xy_lonlat[:, 0], dtype=float)
    lat = np.asarray(xy_lonlat[:, 1], dtype=float)
    xm = np.radians(lon - lon0) * earth_r * math.cos(lat0_rad)
    ym = np.radians(lat - lat0) * earth_r
    return np.column_stack([xm, ym])


def _local_m_to_lonlat(xy_m: np.ndarray, origin_lonlat: tuple[float, float]) -> np.ndarray:
    """Convert local equirectangular meters back to lon/lat degrees."""
    lon0, lat0 = origin_lonlat
    lat0_rad = math.radians(lat0)
    earth_r = 6371000.0
    x = np.asarray(xy_m[:, 0], dtype=float)
    y = np.asarray(xy_m[:, 1], dtype=float)
    lon = lon0 + np.degrees(x / (earth_r * math.cos(lat0_rad)))
    lat = lat0 + np.degrees(y / earth_r)
    return np.column_stack([lon, lat])


def _resolve_xy_mode(xy: np.ndarray, mode: str) -> str:
    mode = str(mode).strip().lower()
    if mode not in {"auto", "meter", "lonlat"}:
        raise ValueError(f"XY_MODE must be auto, meter, or lonlat. Got: {mode}")
    if mode == "auto":
        return "lonlat" if _is_lonlat_xy(xy) else "meter"
    return mode


def _metric_xy_from_original(xy: np.ndarray, mode: str, origin_lonlat: tuple[float, float] | None) -> np.ndarray:
    if mode == "meter":
        return np.asarray(xy, dtype=float)
    if origin_lonlat is None:
        raise ValueError("origin_lonlat is required for lonlat conversion")
    return _lonlat_to_local_m(np.asarray(xy, dtype=float), origin_lonlat)


def _finite_xy_mask(xy: np.ndarray) -> np.ndarray:
    return np.isfinite(xy[:, 0]) & np.isfinite(xy[:, 1])


# ----------------------------------------------------------------------
# Model and route loading
# ----------------------------------------------------------------------


def load_model(params: SimpleNamespace) -> LoadedModel:
    model_file = Path(pget(params, "MODEL_FILE"))
    if not model_file.exists():
        raise FileNotFoundError(f"MODEL_FILE not found: {model_file}")

    df = _read_table_flexible(model_file)

    x_col = _find_column(df, pget(params, "X_COLUMN_CANDIDATES", ["x", "lon", "longitude"]))
    y_col = _find_column(df, pget(params, "Y_COLUMN_CANDIDATES", ["y", "lat", "latitude"]))
    z_col = _find_column(df, pget(params, "Z_COLUMN_CANDIDATES", ["z"]))
    slowness_col = _find_column(df, pget(params, "SLOWNESS_COLUMN_CANDIDATES", ["slowness"]))
    label_col = _find_column(df, pget(params, "LABEL_COLUMN_CANDIDATES", ["label"]))
    label_prefix_col = _find_column(df, pget(params, "LABEL_PREFIX_COLUMN_CANDIDATES", ["label_prefix"]))

    if x_col is None or y_col is None:
        raise ValueError(
            f"Could not detect x/y columns in model file {model_file}. "
            f"Columns found: {list(df.columns)}"
        )

    df[x_col] = _coerce_numeric(df[x_col])
    df[y_col] = _coerce_numeric(df[y_col])
    if z_col is not None:
        df[z_col] = _coerce_numeric(df[z_col])
    if slowness_col is not None:
        df[slowness_col] = _coerce_numeric(df[slowness_col])

    if label_col is None:
        label_col = "label"
        df[label_col] = ""
    if label_prefix_col is None:
        label_prefix_col = "label_prefix"
        df[label_prefix_col] = df[label_col].map(_derive_label_prefix)
    else:
        df[label_prefix_col] = df[label_prefix_col].fillna("").astype(str).str.upper()

    xy_original = df[[x_col, y_col]].to_numpy(dtype=float)
    mode = _resolve_xy_mode(xy_original, pget(params, "XY_MODE", "auto"))
    if mode == "lonlat":
        finite = _finite_xy_mask(xy_original)
        origin_lonlat = (float(np.nanmean(xy_original[finite, 0])), float(np.nanmean(xy_original[finite, 1])))
    else:
        origin_lonlat = None
    xy_metric = _metric_xy_from_original(xy_original, mode, origin_lonlat)

    return LoadedModel(
        df=df,
        x_col=x_col,
        y_col=y_col,
        z_col=z_col,
        slowness_col=slowness_col,
        label_col=label_col,
        label_prefix_col=label_prefix_col,
        xy_original=xy_original,
        xy_metric=xy_metric,
        metric_origin_lonlat=origin_lonlat,
        metric_mode=mode,
    )


def _collect_route_files(params: SimpleNamespace) -> list[Path]:
    globs = _as_list(pget(params, "ROUTE_CSV_GLOBS", "output/02_thetastar_master_plan/*.csv"))
    files: list[Path] = []
    for pattern in globs:
        files.extend(Path(p) for p in glob.glob(str(pattern), recursive=True))
    # Keep only real CSV files, unique, sorted.
    unique = sorted({p.resolve() for p in files if p.is_file() and p.suffix.lower() == ".csv"})
    return unique


def _parse_index_list(value) -> list[int]:
    if pd.isna(value):
        return []
    if isinstance(value, (list, tuple, np.ndarray)):
        return [int(v) for v in value]
    s = str(value).strip()
    if not s:
        return []
    try:
        parsed = ast.literal_eval(s)
        if isinstance(parsed, (list, tuple, np.ndarray)):
            return [int(v) for v in parsed]
    except Exception:
        pass
    # fallback: extract all integers from text like "1, 2, 3" or "[1 2 3]"
    return [int(v) for v in re.findall(r"-?\d+", s)]


def _indices_to_model_xy(
    indices: Sequence[int],
    model: LoadedModel,
    params: SimpleNamespace,
) -> tuple[np.ndarray, np.ndarray]:
    if len(indices) == 0:
        return np.empty((0, 2)), np.empty((0, 2))

    arr = np.asarray(indices, dtype=int)
    n = len(model.df)
    base = str(pget(params, "ROUTE_INDEX_BASE", "auto")).lower()
    if base == "one":
        arr = arr - 1
    elif base == "auto":
        # If all IDs are 1..n and no zero exists, treat as one-based.
        if arr.size > 0 and arr.min() >= 1 and arr.max() <= n and 0 not in set(arr.tolist()):
            # But if max < n, it may still be zero-based subset shifted by chance.
            # Prefer zero-based when every index is valid zero-based and at least one
            # index is close to 0 is absent. For route planners, Python usually writes
            # zero-based row indices, so only force one-based when max == n.
            if arr.max() == n:
                arr = arr - 1

    valid = (arr >= 0) & (arr < n)
    arr = arr[valid]
    if arr.size == 0:
        return np.empty((0, 2)), np.empty((0, 2))
    return model.xy_original[arr], model.xy_metric[arr]


def _route_xy_column_candidates(params: SimpleNamespace) -> tuple[list[str], list[str]]:
    """Return strict route x/y column candidates.

    These are intentionally separate from the model x/y candidates. The route
    reader must not use relaxed matching, because summary tables commonly have
    start_x/end_x/center_x columns that look like coordinates but are not an
    ordered route polyline.
    """
    default_x = [
        "route_x", "route_lon", "path_x", "path_lon", "node_x", "node_lon",
        "x", "lon", "longitude", "x_m", "path_x_m", "route_x_m", "node_x_m",
        "x_original", "easting", "east",
    ]
    default_y = [
        "route_y", "route_lat", "path_y", "path_lat", "node_y", "node_lat",
        "y", "lat", "latitude", "y_m", "path_y_m", "route_y_m", "node_y_m",
        "y_original", "northing", "north",
    ]
    return (
        list(pget(params, "ROUTE_X_COLUMN_CANDIDATES", default_x)),
        list(pget(params, "ROUTE_Y_COLUMN_CANDIDATES", default_y)),
    )


def _detect_route_xy_mode(
    xy_raw: np.ndarray,
    x_col: str,
    y_col: str,
    model: LoadedModel,
    params: SimpleNamespace,
) -> str:
    """Detect whether route columns are lon/lat or metric coordinates."""
    mode = str(pget(params, "ROUTE_XY_MODE", "auto")).strip().lower()
    if mode == "follow_model":
        return model.metric_mode
    if mode in {"meter", "lonlat"}:
        return mode
    if mode != "auto":
        raise ValueError("ROUTE_XY_MODE must be auto, follow_model, meter, or lonlat")

    nx = _norm_col(x_col)
    ny = _norm_col(y_col)
    lon_names = {"lon", "longitude", "route_lon", "path_lon", "node_lon"}
    lat_names = {"lat", "latitude", "route_lat", "path_lat", "node_lat"}
    metric_x_names = {"x_m", "path_x_m", "route_x_m", "node_x_m", "easting", "east"}
    metric_y_names = {"y_m", "path_y_m", "route_y_m", "node_y_m", "northing", "north"}

    if nx in lon_names or ny in lat_names:
        return "lonlat"
    if nx in metric_x_names or ny in metric_y_names:
        return "meter"

    # Generic x/y or path_x/path_y: infer from values.
    return _resolve_xy_mode(xy_raw, "auto")


def _route_xy_to_model_spaces(
    xy_raw: np.ndarray,
    x_col: str,
    y_col: str,
    model: LoadedModel,
    params: SimpleNamespace,
) -> tuple[np.ndarray, np.ndarray, str]:
    """Convert route xy into model-original plotting xy and metric xy."""
    source_mode = _detect_route_xy_mode(xy_raw, x_col, y_col, model, params)

    if source_mode == "lonlat":
        if model.metric_mode == "lonlat":
            origin = model.metric_origin_lonlat
            xy_metric = _metric_xy_from_original(xy_raw, "lonlat", origin)
            xy_original = xy_raw
        else:
            raise ValueError(
                "route columns look like lon/lat but model coordinates are metric; "
                "use a route file with model-index columns or matching metric x/y"
            )
    elif source_mode == "meter":
        xy_metric = np.asarray(xy_raw, dtype=float)
        if model.metric_mode == "lonlat" and model.metric_origin_lonlat is not None:
            # Make plotting consistent when PLOT_USE_ORIGINAL_XY=True.
            xy_original = _local_m_to_lonlat(xy_metric, model.metric_origin_lonlat)
        else:
            xy_original = xy_metric
    else:
        raise ValueError(f"unknown route coordinate mode: {source_mode}")

    return xy_original, xy_metric, source_mode


def _sort_route_df_if_ordered(route_df: pd.DataFrame, params: SimpleNamespace) -> tuple[pd.DataFrame, str]:
    order_col = _find_column_exact(
        route_df,
        pget(
            params,
            "ROUTE_ORDER_COLUMN_CANDIDATES",
            ["path_order", "route_order", "point_order", "node_order", "step", "seq", "sequence", "i"],
        ),
    )
    if order_col is None:
        return route_df, ""
    ordered = route_df.copy()
    ordered[order_col] = _coerce_numeric(ordered[order_col])
    ordered = ordered.sort_values(order_col, kind="mergesort")
    return ordered, f", ordered by {order_col}"


def _model_metric_bbox(model: LoadedModel, margin_m: float) -> tuple[float, float, float, float]:
    xy = model.xy_metric
    finite = _finite_xy_mask(xy)
    if finite.sum() == 0:
        raise ValueError("model has no finite metric xy coordinates")
    xmin = float(np.nanmin(xy[finite, 0])) - margin_m
    xmax = float(np.nanmax(xy[finite, 0])) + margin_m
    ymin = float(np.nanmin(xy[finite, 1])) - margin_m
    ymax = float(np.nanmax(xy[finite, 1])) + margin_m
    return xmin, xmax, ymin, ymax


def _validate_route_geometry(
    xy_metric: np.ndarray,
    model: LoadedModel,
    params: SimpleNamespace,
    route_path: Path,
) -> str:
    """Validate that a parsed route is an ordered path-like geometry."""
    if not bool(pget(params, "VALIDATE_ROUTE_GEOMETRY", True)):
        return ""

    min_unique = int(pget(params, "MIN_ROUTE_UNIQUE_POINTS", 2))
    rounded = np.round(np.asarray(xy_metric, dtype=float), decimals=3)
    unique_count = len(np.unique(rounded, axis=0)) if len(rounded) else 0
    if unique_count < min_unique:
        raise ValueError(f"too few unique route points: {unique_count}")

    hit_buffer_m = float(pget(params, "HIT_BUFFER_M", 300.0))
    margin_m = float(pget(params, "ROUTE_MODEL_BBOX_MARGIN_M", max(1000.0, 2.0 * hit_buffer_m)))
    xmin, xmax, ymin, ymax = _model_metric_bbox(model, margin_m)
    inside = (
        (xy_metric[:, 0] >= xmin)
        & (xy_metric[:, 0] <= xmax)
        & (xy_metric[:, 1] >= ymin)
        & (xy_metric[:, 1] <= ymax)
    )
    inside_fraction = float(np.mean(inside)) if len(inside) else 0.0
    min_inside_fraction = float(pget(params, "ROUTE_MIN_FRACTION_INSIDE_MODEL_BBOX", 0.95))
    if inside_fraction < min_inside_fraction:
        raise ValueError(
            f"route geometry outside model bbox: inside_fraction={inside_fraction:.2f}; "
            "this usually means the wrong x/y columns or coordinate mode were used"
        )

    if len(xy_metric) >= 2:
        seg = np.linalg.norm(np.diff(xy_metric, axis=0), axis=1)
        path_len = float(np.nansum(seg))
        min_len = float(pget(params, "ROUTE_MIN_PATH_LENGTH_M", 1.0))
        if path_len < min_len:
            raise ValueError(f"route path length too short: {path_len:.2f} m")

        max_seg = float(np.nanmax(seg)) if len(seg) else 0.0
        max_allowed = float(pget(params, "ROUTE_MAX_SEGMENT_M", 0.0))
        if bool(pget(params, "REJECT_ROUTES_WITH_LONG_JUMPS", False)) and max_allowed > 0 and max_seg > max_allowed:
            raise ValueError(
                f"route has suspicious long jump: max_segment={max_seg:.1f} m > {max_allowed:.1f} m"
            )
        if max_allowed > 0 and max_seg > max_allowed:
            return f", warning max_segment={max_seg:.1f} m"

    return ""



# ----------------------------------------------------------------------
# Preferred Theta* edge-table route reader: all_route_edges_v4.csv
# ----------------------------------------------------------------------


def _collect_route_edge_file(params: SimpleNamespace) -> Path | None:
    """Return the preferred Theta* edge table, if enabled and available."""
    if not bool(pget(params, "USE_ROUTE_EDGE_FILE", True)):
        return None
    edge_file = Path(str(pget(params, "ROUTE_EDGE_FILE", "output/02_thetastar_master_plan/all_route_edges_v4.csv")))
    if edge_file.exists() and edge_file.is_file():
        return edge_file
    if bool(pget(params, "REQUIRE_ROUTE_EDGE_FILE", False)):
        raise FileNotFoundError(f"ROUTE_EDGE_FILE not found: {edge_file}")
    return None


def _required_edge_column(df: pd.DataFrame, names: Sequence[str], what: str) -> str:
    col = _find_column_exact(df, names)
    if col is None:
        raise ValueError(f"Missing required edge-table column for {what}. Tried: {list(names)}")
    return col


def _make_edge_route_instance_key(base_key: str, part_id: int, n_parts: int) -> str:
    """Build a stable route-instance key after splitting by edge_seq reset."""
    base_key = str(base_key or "route")
    if n_parts <= 1:
        return base_key
    return f"{base_key}__part_{int(part_id):05d}"


def _split_one_edge_group_by_seq_reset(
    group: pd.DataFrame,
    seq_col: str,
    params: SimpleNamespace,
) -> list[pd.DataFrame]:
    """Split one base route_key group into route instances.

    Important v6 fix
    ----------------
    In all_route_edges_v4.csv, ``route_key`` may describe the lane type
    (for example ``forward_main_01``) rather than one complete OD route.
    Therefore a single route_key can contain many routes.  The real route
    boundary is where ``edge_seq`` starts again from 0 or decreases.

    This function preserves the original CSV row order.  Do NOT sort the whole
    route_key group by edge_seq before splitting, because doing that mixes all
    edge_seq=0 rows from many routes, then all edge_seq=1 rows, etc.
    """
    if group.empty:
        return []

    g = group.sort_values("__original_row_order__", kind="mergesort").copy()
    seq = _coerce_numeric(g[seq_col]).to_numpy(dtype=float)

    reset = np.zeros(len(g), dtype=bool)
    reset[0] = True
    if len(g) > 1:
        prev = seq[:-1]
        cur = seq[1:]
        # New route when sequence returns to 0 or otherwise decreases/stalls.
        # ``cur <= prev`` catches reset 45->0 and duplicate/interleaved starts.
        reset[1:] = (cur <= prev) | (cur == 0)

    # Optional stricter split by node continuity.  This is disabled by default
    # because Theta*/LOS-smoothed route exports can sometimes skip sampled
    # cells, but from_node_id/to_node_id should still be continuous for a true
    # edge table.  Enable only for debugging a corrupted export.
    if bool(pget(params, "ROUTE_EDGE_SPLIT_ON_NODE_DISCONTINUITY", False)):
        from_col = _find_column_exact(g, pget(params, "ROUTE_EDGE_FROM_NODE_COLUMN_CANDIDATES", ["from_node_id", "from_idx", "from_node", "node1"]))
        to_col = _find_column_exact(g, pget(params, "ROUTE_EDGE_TO_NODE_COLUMN_CANDIDATES", ["to_node_id", "to_idx", "to_node", "node2"]))
        if from_col is not None and to_col is not None and len(g) > 1:
            from_ids = g[from_col].astype(str).to_numpy()
            to_ids = g[to_col].astype(str).to_numpy()
            node_gap = from_ids[1:] != to_ids[:-1]
            reset[1:] |= node_gap

    part_num = np.cumsum(reset).astype(int) - 1
    out: list[pd.DataFrame] = []
    for _, sub in g.assign(__edge_route_part__=part_num).groupby("__edge_route_part__", sort=False):
        if not sub.empty:
            out.append(sub.drop(columns=["__edge_route_part__"], errors="ignore"))
    return out


def _split_edge_table_into_route_groups(
    edge_df: pd.DataFrame,
    params: SimpleNamespace,
) -> tuple[list[tuple[str, pd.DataFrame]], str]:
    """Split all_route_edges_v4.csv into one DataFrame per actual route.

    Correct v6 logic:
        1. preserve original CSV row order;
        2. optionally separate by base ``route_key``;
        3. inside each base key, cut a new route whenever ``edge_seq`` resets
           to 0 or decreases;
        4. keep the sub-route in file order for reconstruction.

    Why this is necessary:
        ``route_key`` values such as ``forward_main_01`` can repeat for many
        OD routes.  Sorting the whole route_key group by edge_seq incorrectly
        connects all edge 0 rows together, then all edge 1 rows, creating fake
        disconnected route lines and corrupting hit-density.
    """
    key_col = _find_column_exact(
        edge_df,
        pget(
            params,
            "ROUTE_KEY_COLUMN_CANDIDATES",
            [
                "route_key", "route_id", "path_key", "path_id", "pair_key",
                "label_pair", "route_name", "pair_name", "od_key",
            ],
        ),
    )
    seq_col = _required_edge_column(
        edge_df,
        pget(params, "ROUTE_EDGE_SEQ_COLUMN_CANDIDATES", ["edge_seq", "seq", "edge_order"]),
        "edge sequence",
    )

    work = edge_df.copy()
    work[seq_col] = _coerce_numeric(work[seq_col])
    work = work[work[seq_col].notna()].copy()
    # Original row order must be assigned after filtering, then preserved.
    work["__original_row_order__"] = np.arange(len(work), dtype=int)
    work = work.sort_values("__original_row_order__", kind="mergesort")

    groups: list[tuple[str, pd.DataFrame]] = []

    if key_col is not None:
        base_note = f"base grouped by {key_col}; split inside each base key by {seq_col} reset/decrease; file order preserved"
        for base_key, base_group in work.groupby(key_col, sort=False, dropna=False):
            base_key_s = "" if pd.isna(base_key) else str(base_key)
            parts = _split_one_edge_group_by_seq_reset(base_group, seq_col, params)
            for i, part in enumerate(parts):
                rk = _make_edge_route_instance_key(base_key_s, i, len(parts))
                groups.append((rk, part))
        return groups, base_note

    # No route_key column. Split the whole file by edge_seq reset/decrease.
    parts = _split_one_edge_group_by_seq_reset(work, seq_col, params)
    for i, part in enumerate(parts):
        groups.append((f"edge_seq_route_{i:05d}", part))
    return groups, f"no route_key column; split whole edge table by {seq_col} reset/decrease; file order preserved"

def _edge_group_to_route_xy(
    group: pd.DataFrame,
    edge_file: Path,
    route_key: str,
    model: LoadedModel,
    params: SimpleNamespace,
) -> tuple[np.ndarray, np.ndarray, str]:
    """Reconstruct one route polyline from x1/y1 -> x2/y2 edge rows."""
    x1_col = _required_edge_column(group, pget(params, "ROUTE_EDGE_X1_COLUMN_CANDIDATES", ["x1", "from_x", "x_from"]), "edge x1")
    y1_col = _required_edge_column(group, pget(params, "ROUTE_EDGE_Y1_COLUMN_CANDIDATES", ["y1", "from_y", "y_from"]), "edge y1")
    x2_col = _required_edge_column(group, pget(params, "ROUTE_EDGE_X2_COLUMN_CANDIDATES", ["x2", "to_x", "x_to"]), "edge x2")
    y2_col = _required_edge_column(group, pget(params, "ROUTE_EDGE_Y2_COLUMN_CANDIDATES", ["y2", "to_y", "y_to"]), "edge y2")
    seq_col = _required_edge_column(group, pget(params, "ROUTE_EDGE_SEQ_COLUMN_CANDIDATES", ["edge_seq", "seq", "edge_order"]), "edge sequence")
    dist_col = _find_column_exact(group, pget(params, "ROUTE_EDGE_DISTANCE_COLUMN_CANDIDATES", ["edge_distance_m", "distance_m", "edge_length_m"]))

    g = group.copy()
    for c in [x1_col, y1_col, x2_col, y2_col, seq_col]:
        g[c] = _coerce_numeric(g[c])
    g = g.dropna(subset=[x1_col, y1_col, x2_col, y2_col, seq_col])
    if g.empty:
        raise ValueError(f"route_key={route_key}: no finite edge coordinates")

    # v6: keep the original file order after the edge_seq-reset split.
    # Sorting by edge_seq here would again mix duplicate 0..N sequences if a
    # base group was not perfectly cut.  Only use edge_seq sorting if explicitly
    # requested for a known one-route-per-key table.
    order_mode = str(pget(params, "ROUTE_EDGE_ORDER_MODE", "file_order_after_reset_split")).strip().lower()
    if order_mode in ("edge_seq", "seq", "sort_by_edge_seq"):
        g = g.sort_values([seq_col, "__original_row_order__"] if "__original_row_order__" in g.columns else [seq_col], kind="mergesort")
    elif "__original_row_order__" in g.columns:
        g = g.sort_values("__original_row_order__", kind="mergesort")

    raw_points = []
    first = g.iloc[0]
    raw_points.append([float(first[x1_col]), float(first[y1_col])])
    for _, row in g.iterrows():
        raw_points.append([float(row[x2_col]), float(row[y2_col])])
    xy_raw = np.asarray(raw_points, dtype=float)

    # Convert route coordinates into model-original and metric coordinate systems.
    xy_original, xy_metric, source_mode = _route_xy_to_model_spaces(xy_raw, x1_col, y1_col, model, params)

    # Check whether edge rows are connected. This is a route-key/edge-seq sanity check.
    # Use metric coordinates after conversion, so tolerance is in meters.
    disconnected = 0
    if len(g) >= 2:
        x1y1 = g[[x1_col, y1_col]].to_numpy(dtype=float)
        x2y2 = g[[x2_col, y2_col]].to_numpy(dtype=float)
        _, x1y1_metric, _ = _route_xy_to_model_spaces(x1y1, x1_col, y1_col, model, params)
        _, x2y2_metric, _ = _route_xy_to_model_spaces(x2y2, x2_col, y2_col, model, params)
        gap = np.linalg.norm(x1y1_metric[1:] - x2y2_metric[:-1], axis=1)
        tol = float(pget(params, "ROUTE_EDGE_CONNECT_TOLERANCE_M", 2.0))
        disconnected = int(np.sum(gap > tol))
        if disconnected > 0 and bool(pget(params, "REJECT_DISCONNECTED_ROUTE_EDGES", True)):
            raise ValueError(
                f"route_key={route_key}: disconnected ordered edges: {disconnected} gaps > {tol:.2f} m. "
                "Check route_key and edge_seq grouping."
            )

    validation_note = _validate_route_geometry(xy_metric, model, params, edge_file)

    # Optional route distance diagnostics from edge_distance_m, if present.
    distance_note = ""
    if dist_col is not None:
        edge_d = _coerce_numeric(g[dist_col]).dropna().to_numpy(dtype=float)
        if edge_d.size:
            distance_note = f", edge_distance_sum={float(np.nansum(edge_d)):.1f} m"

    return (
        xy_original,
        xy_metric,
        f"edge-table route_key={route_key}; edges={len(g)}; order={str(pget(params, 'ROUTE_EDGE_ORDER_MODE', 'file_order_after_reset_split'))}; "
        f"mode={source_mode}; disconnected_gaps={disconnected}{distance_note}{validation_note}",
    )


def _load_routes_from_edge_table(
    edge_file: Path,
    model: LoadedModel,
    params: SimpleNamespace,
) -> tuple[list[tuple[str, np.ndarray, np.ndarray, str]], list[LoadedRoute], str]:
    """Load all route polylines from all_route_edges_v4.csv."""
    edge_df = _read_table_flexible(edge_file)
    groups, grouping_note = _split_edge_table_into_route_groups(edge_df, params)
    routes: list[tuple[str, np.ndarray, np.ndarray, str]] = []
    skipped: list[LoadedRoute] = []

    min_route_points = int(pget(params, "MIN_ROUTE_POINTS", 2))
    for route_key, group in groups:
        try:
            xy_original, xy_metric, reason = _edge_group_to_route_xy(group, edge_file, route_key, model, params)
            if len(xy_metric) < min_route_points:
                raise ValueError(f"route_key={route_key}: too few route points after edge reconstruction: {len(xy_metric)}")
            routes.append((route_key, xy_original, xy_metric, reason))
        except Exception as exc:
            skipped.append(
                LoadedRoute(
                    path=edge_file,
                    xy_original=np.empty((0, 2)),
                    xy_metric=np.empty((0, 2)),
                    n_raw_points=0,
                    n_dense_points=0,
                    hit_nodes=0,
                    status="skipped",
                    reason=str(exc),
                    route_key=str(route_key),
                    source_kind="edge_table",
                )
            )
    return routes, skipped, grouping_note

def _extract_route_xy_from_df(
    route_df: pd.DataFrame,
    route_path: Path,
    model: LoadedModel,
    params: SimpleNamespace,
) -> tuple[np.ndarray, np.ndarray, str]:
    """Return route original and metric xy arrays.

    Important v3 fix: route geometry columns are matched strictly. This prevents
    summary columns such as start_x/end_x/center_x from being misread as a
    polyline, which would corrupt both route-line figures and hit-count density.
    """
    route_df, order_note = _sort_route_df_if_ordered(route_df, params)

    x_candidates, y_candidates = _route_xy_column_candidates(params)
    x_col = _find_column_exact(route_df, x_candidates)
    y_col = _find_column_exact(route_df, y_candidates)

    if x_col is not None and y_col is not None:
        x = _coerce_numeric(route_df[x_col])
        y = _coerce_numeric(route_df[y_col])
        xy_raw = np.column_stack([x.to_numpy(dtype=float), y.to_numpy(dtype=float)])
        finite = _finite_xy_mask(xy_raw)
        xy_raw = xy_raw[finite]
        xy_original, xy_metric, source_mode = _route_xy_to_model_spaces(xy_raw, x_col, y_col, model, params)
        validation_note = _validate_route_geometry(xy_metric, model, params, route_path)
        return xy_original, xy_metric, f"strict xy columns: {x_col}, {y_col}; mode={source_mode}{order_note}{validation_note}"

    # Try one node-index-per-row route format. Use strict matching only so
    # start_idx/end_idx in summary files are not misused as paths.
    idx_col = _find_column_exact(route_df, pget(params, "ROUTE_INDEX_COLUMN_CANDIDATES", []))
    if idx_col is not None:
        route_df, order_note = _sort_route_df_if_ordered(route_df, params)
        indices = _coerce_numeric(route_df[idx_col]).dropna().astype(int).tolist()
        xy_original, xy_metric = _indices_to_model_xy(indices, model, params)
        validation_note = _validate_route_geometry(xy_metric, model, params, route_path)
        return xy_original, xy_metric, f"strict index column: {idx_col}{order_note}{validation_note}"

    # Try single-row/list route format. Use strict matching only.
    list_col = _find_column_exact(route_df, pget(params, "ROUTE_INDEX_LIST_COLUMN_CANDIDATES", []))
    if list_col is not None:
        indices: list[int] = []
        for value in route_df[list_col].dropna().tolist():
            indices.extend(_parse_index_list(value))
        xy_original, xy_metric = _indices_to_model_xy(indices, model, params)
        validation_note = _validate_route_geometry(xy_metric, model, params, route_path)
        return xy_original, xy_metric, f"strict index-list column: {list_col}{validation_note}"

    raise ValueError(
        f"No strict route xy/index columns detected in {route_path.name}. "
        f"Columns found: {list(route_df.columns)}"
    )

def densify_polyline(xy_metric: np.ndarray, step_m: float) -> np.ndarray:
    """Densify a polyline in metric coordinates."""
    xy = np.asarray(xy_metric, dtype=float)
    if len(xy) < 2:
        return xy.copy()
    if step_m <= 0:
        return xy.copy()

    out = [xy[0]]
    for a, b in zip(xy[:-1], xy[1:]):
        if not (np.all(np.isfinite(a)) and np.all(np.isfinite(b))):
            continue
        dist = float(np.linalg.norm(b - a))
        if dist == 0:
            continue
        n_steps = max(1, int(math.ceil(dist / step_m)))
        for k in range(1, n_steps + 1):
            t = k / n_steps
            out.append(a * (1.0 - t) + b * t)
    return np.asarray(out, dtype=float)


# ----------------------------------------------------------------------
# Eligibility and hit counting
# ----------------------------------------------------------------------


def build_eligible_mask(model: LoadedModel, params: SimpleNamespace) -> np.ndarray:
    df = model.df
    mask = _finite_xy_mask(model.xy_metric)

    exclude_prefixes = {str(v).upper() for v in _as_list(pget(params, "EXCLUDE_LABEL_PREFIXES", []))}
    exclude_labels = {str(v).upper() for v in _as_list(pget(params, "EXCLUDE_LABELS", []))}

    if exclude_prefixes:
        prefixes = df[model.label_prefix_col].fillna("").astype(str).str.upper()
        mask &= ~prefixes.isin(exclude_prefixes).to_numpy()

    if exclude_labels:
        labels = df[model.label_col].fillna("").astype(str).str.upper()
        mask &= ~labels.isin(exclude_labels).to_numpy()

    if bool(pget(params, "USE_ONLY_FLYABLE_MODEL_NODES", True)) and model.slowness_col is not None:
        slow = _coerce_numeric(df[model.slowness_col]).to_numpy(dtype=float)
        threshold = float(pget(params, "NOFLY_SLOWNESS_THRESHOLD", 10.0))
        mode = str(pget(params, "NOFLY_THRESHOLD_MODE", "greater_equal")).lower()
        if mode == "greater_equal":
            mask &= ~(slow >= threshold)
        elif mode == "greater":
            mask &= ~(slow > threshold)
        elif mode == "equal":
            mask &= ~(np.isclose(slow, threshold))
        else:
            raise ValueError(f"Unknown NOFLY_THRESHOLD_MODE: {mode}")

    return mask


def _count_hits_for_loaded_routes(
    loaded_routes: list[tuple[str, Path, np.ndarray, np.ndarray, str, str]],
    model: LoadedModel,
    params: SimpleNamespace,
    eligible_indices: np.ndarray,
    tree: cKDTree,
    hit_count: np.ndarray,
) -> tuple[list[LoadedRoute], list[LoadedRoute]]:
    """Count route hits for already reconstructed routes."""
    hit_buffer_m = float(pget(params, "HIT_BUFFER_M", 300.0))
    step_m = float(pget(params, "ROUTE_DENSIFY_STEP_M", 50.0))
    min_route_points = int(pget(params, "MIN_ROUTE_POINTS", 2))

    processed: list[LoadedRoute] = []
    skipped: list[LoadedRoute] = []

    for route_key, route_path, xy_original, xy_metric, reason, source_kind in loaded_routes:
        try:
            if len(xy_metric) < min_route_points:
                raise ValueError(f"too few route points after parsing: {len(xy_metric)}")

            dense = densify_polyline(xy_metric, step_m)
            if len(dense) < min_route_points:
                raise ValueError(f"too few dense route points: {len(dense)}")

            query = tree.query_ball_point(dense, r=hit_buffer_m)
            if len(query) == 0:
                local_hits = np.array([], dtype=int)
            else:
                non_empty = [np.asarray(q, dtype=int) for q in query if len(q) > 0]
                local_hits = np.unique(np.concatenate(non_empty)) if non_empty else np.array([], dtype=int)

            global_hits = eligible_indices[local_hits]
            hit_count[global_hits] += 1

            processed.append(
                LoadedRoute(
                    path=route_path,
                    xy_original=xy_original,
                    xy_metric=xy_metric,
                    n_raw_points=len(xy_metric),
                    n_dense_points=len(dense),
                    hit_nodes=int(len(global_hits)),
                    status="processed",
                    reason=reason,
                    route_key=str(route_key),
                    source_kind=source_kind,
                )
            )
        except Exception as exc:
            skipped.append(
                LoadedRoute(
                    path=route_path,
                    xy_original=np.empty((0, 2)),
                    xy_metric=np.empty((0, 2)),
                    n_raw_points=0,
                    n_dense_points=0,
                    hit_nodes=0,
                    status="skipped",
                    reason=str(exc),
                    route_key=str(route_key),
                    source_kind=source_kind,
                )
            )

    return processed, skipped


def compute_route_hits(
    model: LoadedModel,
    params: SimpleNamespace,
    eligible_mask: np.ndarray,
) -> tuple[np.ndarray, list[LoadedRoute], list[LoadedRoute]]:
    hit_count = np.zeros(len(model.df), dtype=np.int32)
    eligible_indices = np.flatnonzero(eligible_mask)
    if eligible_indices.size == 0:
        raise ValueError("No eligible model nodes remain after exclusion/flyability filters.")

    tree = cKDTree(model.xy_metric[eligible_indices])
    processed: list[LoadedRoute] = []
    skipped: list[LoadedRoute] = []

    # Preferred v5 logic: read all_route_edges_v4.csv and cut each route by route_key,
    # or by edge_seq reset if route_key is missing.
    edge_file = _collect_route_edge_file(params)
    if edge_file is not None:
        print(f"[kmean] Reading preferred route edge table: {edge_file}")
        routes, edge_skipped, grouping_note = _load_routes_from_edge_table(edge_file, model, params)
        print(f"[kmean] Edge table grouping: {grouping_note}")
        print(f"[kmean] Edge-table reconstructed routes: {len(routes):,}")
        loaded_routes = [
            (route_key, edge_file, xy_original, xy_metric, reason, "edge_table")
            for route_key, xy_original, xy_metric, reason in routes
        ]
        processed, skipped2 = _count_hits_for_loaded_routes(
            loaded_routes, model, params, eligible_indices, tree, hit_count
        )
        skipped = edge_skipped + skipped2
        if processed or bool(pget(params, "EDGE_FILE_DISABLE_LEGACY_FALLBACK", True)):
            if not processed:
                examples = "\n".join(f"  - {r.route_key or r.path.name}: {r.reason}" for r in skipped[:10])
                raise RuntimeError(
                    "No valid routes were reconstructed from ROUTE_EDGE_FILE.\n"
                    f"First skipped examples:\n{examples}"
                )
            return hit_count, processed, skipped

    # Legacy fallback: route CSV files with ordered x/y or model-index columns.
    route_files = _collect_route_files(params)
    if not route_files:
        raise FileNotFoundError(
            "No route edge table or legacy route CSV files found. Check ROUTE_EDGE_FILE and ROUTE_CSV_GLOBS."
        )

    print("[kmean] WARNING: using legacy per-route CSV reader; preferred all_route_edges_v4.csv was not used.")
    loaded_routes: list[tuple[str, Path, np.ndarray, np.ndarray, str, str]] = []
    for route_path in route_files:
        try:
            route_df = _read_table_flexible(route_path)
            xy_original, xy_metric, reason = _extract_route_xy_from_df(route_df, route_path, model, params)
            loaded_routes.append((route_path.stem, route_path, xy_original, xy_metric, reason, "legacy_csv"))
        except Exception as exc:
            skipped.append(
                LoadedRoute(
                    path=route_path,
                    xy_original=np.empty((0, 2)),
                    xy_metric=np.empty((0, 2)),
                    n_raw_points=0,
                    n_dense_points=0,
                    hit_nodes=0,
                    status="skipped",
                    reason=str(exc),
                    route_key=route_path.stem,
                    source_kind="legacy_csv",
                )
            )

    processed2, skipped2 = _count_hits_for_loaded_routes(
        loaded_routes, model, params, eligible_indices, tree, hit_count
    )
    processed += processed2
    skipped += skipped2

    if not processed:
        examples = "\n".join(f"  - {r.route_key or r.path.name}: {r.reason}" for r in skipped[:10])
        raise RuntimeError(
            "All route CSV files were skipped. Check route CSV columns.\n"
            f"First skipped examples:\n{examples}"
        )

    return hit_count, processed, skipped

# ----------------------------------------------------------------------
# KMeans candidate selection
# ----------------------------------------------------------------------


def _threshold_pool_by_hit(
    hit_count: np.ndarray,
    eligible_mask: np.ndarray,
    min_hit_count: int,
    percentile: float,
    min_needed: int,
) -> np.ndarray:
    eligible_indices = np.flatnonzero(eligible_mask)
    hits = hit_count[eligible_indices]

    pool = eligible_indices[hits >= int(min_hit_count)]
    if len(pool) >= min_needed:
        return pool

    positive = hits[hits > 0]
    if positive.size > 0:
        pct = float(np.clip(percentile, 0.0, 100.0))
        threshold = np.percentile(positive, pct)
        pool = eligible_indices[hits >= threshold]
        if len(pool) >= min_needed:
            return pool

    # Last fallback: use top hit nodes among eligible nodes.
    order = np.argsort(-hits)
    take = min(len(order), max(min_needed, 1))
    return eligible_indices[order[:take]]


def _minor_pool(
    hit_count: np.ndarray,
    eligible_mask: np.ndarray,
    params: SimpleNamespace,
    min_needed: int,
) -> np.ndarray:
    mode = str(pget(params, "MINOR_POOL_MODE", "all_eligible")).lower()
    eligible_indices = np.flatnonzero(eligible_mask)
    hits = hit_count[eligible_indices]

    if mode == "all_eligible":
        return eligible_indices
    if mode == "hit_positive":
        pool = eligible_indices[hits >= int(pget(params, "MINOR_MIN_HIT_COUNT", 1))]
        if len(pool) >= min_needed:
            return pool
        return eligible_indices[np.argsort(-hits)[: min(len(eligible_indices), min_needed)]]
    if mode == "percentile":
        return _threshold_pool_by_hit(
            hit_count=hit_count,
            eligible_mask=eligible_mask,
            min_hit_count=int(pget(params, "MINOR_MIN_HIT_COUNT", 1)),
            percentile=float(pget(params, "MINOR_HIT_PERCENTILE", 40.0)),
            min_needed=min_needed,
        )
    raise ValueError(f"Unknown MINOR_POOL_MODE: {mode}")


def _sample_weights(hit_count: np.ndarray, indices: np.ndarray, params: SimpleNamespace) -> np.ndarray:
    power = float(pget(params, "HIT_WEIGHT_POWER", 1.0))
    hits = np.asarray(hit_count[indices], dtype=float)
    return 1.0 + np.power(np.maximum(hits, 0.0), power)


def _too_close_to_existing(
    xy_metric: np.ndarray,
    idx: int,
    selected_indices: list[int],
    min_sep_m: float,
) -> bool:
    if min_sep_m <= 0 or not selected_indices:
        return False
    p = xy_metric[idx]
    existing = xy_metric[np.asarray(selected_indices, dtype=int)]
    d = np.linalg.norm(existing - p, axis=1)
    return bool(np.any(d < min_sep_m))


def _select_cluster_representative(
    cluster_indices: np.ndarray,
    center: np.ndarray,
    model: LoadedModel,
    hit_count: np.ndarray,
    params: SimpleNamespace,
    selected_indices: list[int],
    min_sep_m: float,
) -> int | None:
    method = str(pget(params, "REPRESENTATIVE_METHOD", "max_hit_then_center")).lower()
    xy = model.xy_metric[cluster_indices]
    dist = np.linalg.norm(xy - center, axis=1)
    hits = hit_count[cluster_indices]

    if method == "nearest_center":
        order = np.argsort(dist)
    elif method == "max_hit_then_center":
        # Highest hit first; tie-break by nearest center.
        order = np.lexsort((dist, -hits))
    else:
        raise ValueError(f"Unknown REPRESENTATIVE_METHOD: {method}")

    for local in order:
        idx = int(cluster_indices[local])
        if not _too_close_to_existing(model.xy_metric, idx, selected_indices, min_sep_m):
            return idx
    return None


def _fit_kmeans_candidates(
    pool_indices: np.ndarray,
    n_candidates: int,
    candidate_type: str,
    model: LoadedModel,
    hit_count: np.ndarray,
    params: SimpleNamespace,
    already_selected: list[int] | None = None,
) -> list[dict]:
    if KMeans is None:
        raise ImportError(
            "scikit-learn is required for KMeans. Install with: pip install scikit-learn"
        ) from _SKLEARN_IMPORT_ERROR

    pool_indices = np.asarray(pool_indices, dtype=int)
    pool_indices = np.unique(pool_indices)
    if already_selected is None:
        already_selected = []

    # Remove nodes that are too close to already selected candidates before KMeans.
    min_sep_m = float(pget(params, "CANDIDATE_MIN_SEPARATION_M", 300.0))
    if already_selected and min_sep_m > 0:
        selected_xy = model.xy_metric[np.asarray(already_selected, dtype=int)]
        tree = cKDTree(selected_xy)
        dist, _ = tree.query(model.xy_metric[pool_indices], k=1)
        pool_indices = pool_indices[dist >= min_sep_m]

    if len(pool_indices) == 0 or n_candidates <= 0:
        return []

    n_clusters = min(int(n_candidates), len(pool_indices))
    xy = model.xy_metric[pool_indices]
    weights = _sample_weights(hit_count, pool_indices, params)

    kmeans = KMeans(
        n_clusters=n_clusters,
        random_state=int(pget(params, "KMEANS_RANDOM_STATE", 42)),
        n_init=int(pget(params, "KMEANS_N_INIT", 20)),
        max_iter=int(pget(params, "KMEANS_MAX_ITER", 300)),
    )
    labels = kmeans.fit_predict(xy, sample_weight=weights)

    selected = list(already_selected)
    rows: list[dict] = []
    for cluster_id in range(n_clusters):
        members = pool_indices[labels == cluster_id]
        if len(members) == 0:
            continue
        center = kmeans.cluster_centers_[cluster_id]
        idx = _select_cluster_representative(
            members,
            center,
            model=model,
            hit_count=hit_count,
            params=params,
            selected_indices=selected,
            min_sep_m=min_sep_m,
        )
        if idx is None:
            continue
        selected.append(idx)
        center_dist = float(np.linalg.norm(model.xy_metric[idx] - center))
        rows.append(
            {
                "candidate_type": candidate_type,
                "cluster_id": int(cluster_id),
                "model_index": int(idx),
                "x": float(model.xy_original[idx, 0]),
                "y": float(model.xy_original[idx, 1]),
                "x_m": float(model.xy_metric[idx, 0]),
                "y_m": float(model.xy_metric[idx, 1]),
                "z": float(model.df[model.z_col].iloc[idx]) if model.z_col is not None and pd.notna(model.df[model.z_col].iloc[idx]) else np.nan,
                "slowness": float(model.df[model.slowness_col].iloc[idx]) if model.slowness_col is not None and pd.notna(model.df[model.slowness_col].iloc[idx]) else np.nan,
                "label": str(model.df[model.label_col].iloc[idx]) if model.label_col is not None else "",
                "label_prefix": str(model.df[model.label_prefix_col].iloc[idx]) if model.label_prefix_col is not None else "",
                "route_hit_count": int(hit_count[idx]),
                "cluster_member_count": int(len(members)),
                "cluster_hit_sum": int(hit_count[members].sum()),
                "distance_to_kmean_center_m": center_dist,
            }
        )

    # Sort candidates by type priority and hit count for cleaner output.
    rows.sort(key=lambda r: (-int(r["route_hit_count"]), int(r["cluster_id"])))
    return rows


def _auto_count_base_size(
    base_name: str,
    *,
    eligible_mask: np.ndarray,
    hit_count: np.ndarray,
    pool_indices: np.ndarray | None = None,
) -> int:
    """Return denominator for automatic candidate-count percentage.

    Supported base names:
        eligible     : all eligible candidate nodes
        hit_positive : eligible nodes with route_hit_count > 0
        pool         : the current candidate pool passed to KMeans
    """
    base = str(base_name or "eligible").strip().lower()
    eligible_indices = np.flatnonzero(eligible_mask)

    if base in ("eligible", "all_eligible", "all"):
        return int(len(eligible_indices))

    if base in ("hit_positive", "positive", "hit", "route_hit"):
        if len(eligible_indices) == 0:
            return 0
        return int(np.count_nonzero(hit_count[eligible_indices] > 0))

    if base in ("pool", "candidate_pool", "kmeans_pool"):
        return int(0 if pool_indices is None else len(np.unique(np.asarray(pool_indices, dtype=int))))

    raise ValueError(
        f"Unknown automatic count base: {base_name}. "
        "Use eligible, hit_positive, or pool."
    )


def _count_from_percentage(
    *,
    percent: float,
    base_size: int,
    min_count: int,
    max_count: int,
    fallback_count: int,
) -> int:
    """Convert a percent value into a safe candidate count.

    Important: percent is written as percent, not fraction.
    Example: 0.10 means 0.10% of the chosen base.
    """
    try:
        pct = float(percent)
    except Exception:
        pct = 0.0

    base_size = max(0, int(base_size))
    min_count = max(0, int(min_count))
    max_count = max(0, int(max_count))
    fallback_count = max(0, int(fallback_count))

    if base_size <= 0 or pct <= 0.0:
        n = fallback_count
    else:
        n = int(math.ceil(base_size * pct / 100.0))

    if min_count > 0:
        n = max(n, min_count)
    if max_count > 0:
        n = min(n, max_count)
    if base_size > 0:
        n = min(n, base_size)
    return max(0, int(n))


def _auto_candidate_counts_from_percentage(
    *,
    params: SimpleNamespace,
    eligible_mask: np.ndarray,
    hit_count: np.ndarray,
    major_pool: np.ndarray,
    minor_pool: np.ndarray,
) -> tuple[int, int, dict[str, object]]:
    """Auto-define major/minor candidate numbers when both manual counts are 0.

    Rule requested for v8:
        if N_MAJOR_CANDIDATES == 0 and N_MINOR_CANDIDATES == 0:
            use percentage-based automatic candidate counts.

    The percentages are controlled by params and can use different bases for
    major and minor candidates. This keeps the old manual option untouched.
    """
    major_base_name = str(pget(params, "AUTO_MAJOR_COUNT_BASE", "hit_positive"))
    minor_base_name = str(pget(params, "AUTO_MINOR_COUNT_BASE", "eligible"))

    major_base_size = _auto_count_base_size(
        major_base_name,
        eligible_mask=eligible_mask,
        hit_count=hit_count,
        pool_indices=major_pool,
    )
    minor_base_size = _auto_count_base_size(
        minor_base_name,
        eligible_mask=eligible_mask,
        hit_count=hit_count,
        pool_indices=minor_pool,
    )

    n_major = _count_from_percentage(
        percent=float(pget(params, "AUTO_MAJOR_COUNT_PERCENT", 0.20)),
        base_size=major_base_size,
        min_count=int(pget(params, "AUTO_MAJOR_MIN_CANDIDATES", 3)),
        max_count=int(pget(params, "AUTO_MAJOR_MAX_CANDIDATES", 40)),
        fallback_count=int(pget(params, "AUTO_MAJOR_FALLBACK_CANDIDATES", 8)),
    )
    n_minor = _count_from_percentage(
        percent=float(pget(params, "AUTO_MINOR_COUNT_PERCENT", 0.15)),
        base_size=minor_base_size,
        min_count=int(pget(params, "AUTO_MINOR_MIN_CANDIDATES", 5)),
        max_count=int(pget(params, "AUTO_MINOR_MAX_CANDIDATES", 80)),
        fallback_count=int(pget(params, "AUTO_MINOR_FALLBACK_CANDIDATES", 12)),
    )

    # Never ask KMeans for more clusters than available pool points.
    n_major = min(n_major, int(len(np.unique(np.asarray(major_pool, dtype=int)))))
    n_minor = min(n_minor, int(len(np.unique(np.asarray(minor_pool, dtype=int)))))

    meta = {
        "mode": "auto_percentage",
        "major_count_base": major_base_name,
        "major_base_size": int(major_base_size),
        "major_percent": float(pget(params, "AUTO_MAJOR_COUNT_PERCENT", 0.20)),
        "major_count": int(n_major),
        "minor_count_base": minor_base_name,
        "minor_base_size": int(minor_base_size),
        "minor_percent": float(pget(params, "AUTO_MINOR_COUNT_PERCENT", 0.15)),
        "minor_count": int(n_minor),
    }
    return int(n_major), int(n_minor), meta


def select_candidates(
    model: LoadedModel,
    params: SimpleNamespace,
    eligible_mask: np.ndarray,
    hit_count: np.ndarray,
) -> pd.DataFrame:
    requested_n_major = int(pget(params, "N_MAJOR_CANDIDATES", 12))
    requested_n_minor = int(pget(params, "N_MINOR_CANDIDATES", 20))
    min_sep_m = float(pget(params, "CANDIDATE_MIN_SEPARATION_M", 300.0))

    # v8 behavior:
    #   - normal/manual mode: use N_MAJOR_CANDIDATES and N_MINOR_CANDIDATES
    #   - auto mode only when BOTH are zero: derive counts from percentages
    use_auto_percentage_counts = (requested_n_major == 0 and requested_n_minor == 0)

    major_min_needed = 1 if use_auto_percentage_counts else max(requested_n_major, 1)
    major_pool = _threshold_pool_by_hit(
        hit_count=hit_count,
        eligible_mask=eligible_mask,
        min_hit_count=int(pget(params, "MAJOR_MIN_HIT_COUNT", 2)),
        percentile=float(pget(params, "MAJOR_HIT_PERCENTILE", 80.0)),
        min_needed=major_min_needed,
    )

    minor_min_needed = 1 if use_auto_percentage_counts else max(requested_n_minor, 1)
    minor_pool = _minor_pool(hit_count, eligible_mask, params, min_needed=minor_min_needed)

    if use_auto_percentage_counts:
        n_major, n_minor, auto_meta = _auto_candidate_counts_from_percentage(
            params=params,
            eligible_mask=eligible_mask,
            hit_count=hit_count,
            major_pool=major_pool,
            minor_pool=minor_pool,
        )
        print(
            "[kmean] Auto candidate count mode: "
            f"major={n_major} "
            f"({auto_meta['major_percent']}% of {auto_meta['major_count_base']}={auto_meta['major_base_size']}), "
            f"minor={n_minor} "
            f"({auto_meta['minor_percent']}% of {auto_meta['minor_count_base']}={auto_meta['minor_base_size']})"
        )
    else:
        n_major = max(0, int(requested_n_major))
        n_minor = max(0, int(requested_n_minor))
        print(f"[kmean] Manual candidate count mode: major={n_major}, minor={n_minor}")

    major_rows = _fit_kmeans_candidates(
        major_pool,
        n_major,
        "major",
        model=model,
        hit_count=hit_count,
        params=params,
        already_selected=[],
    )

    selected_major = [int(r["model_index"]) for r in major_rows]

    # Minor candidates are intended as coverage/back-up nodes, so remove major
    # nodes and optionally remove the immediate major neighborhood.
    if selected_major:
        minor_pool = np.setdiff1d(minor_pool, np.asarray(selected_major, dtype=int), assume_unique=False)
        if min_sep_m > 0 and len(minor_pool) > 0:
            tree = cKDTree(model.xy_metric[np.asarray(selected_major, dtype=int)])
            dist, _ = tree.query(model.xy_metric[minor_pool], k=1)
            minor_pool = minor_pool[dist >= min_sep_m]

    minor_rows = _fit_kmeans_candidates(
        minor_pool,
        n_minor,
        "minor",
        model=model,
        hit_count=hit_count,
        params=params,
        already_selected=selected_major,
    )

    rows = major_rows + minor_rows
    if not rows:
        return pd.DataFrame()

    out = pd.DataFrame(rows)
    out.insert(0, "candidate_id", [f"TN{i + 1:03d}" for i in range(len(out))])
    type_rank = out["candidate_type"].map({"major": 0, "minor": 1}).fillna(9)
    out = out.assign(_rank=type_rank).sort_values(["_rank", "route_hit_count"], ascending=[True, False]).drop(columns="_rank")
    out["candidate_id"] = [f"TN{i + 1:03d}" for i in range(len(out))]
    return out.reset_index(drop=True)


# ----------------------------------------------------------------------
# Output tables and figures
# ----------------------------------------------------------------------


def _write_params_snapshot(params: SimpleNamespace, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    src = Path(pget(params, "PARAMS_FILE", ""))
    if src.exists():
        shutil.copy2(src, output_dir / "kmean.params.snapshot")


def build_nofly_mask(model: LoadedModel, params: SimpleNamespace) -> np.ndarray:
    """Mask model nodes that are no-fly by slowness threshold only.

    This is separate from eligible_mask because eligible_mask also excludes
    objectives (DB/DK/FLZ/RA).  For visual checking on Figure 04, the user
    specifically requested the no-fly zone overlay.
    """
    mask = _finite_xy_mask(model.xy_metric)
    if model.slowness_col is None:
        return np.zeros(len(model.df), dtype=bool)

    slow = _coerce_numeric(model.df[model.slowness_col]).to_numpy(dtype=float)
    threshold = float(pget(params, "NOFLY_SLOWNESS_THRESHOLD", 10.0))
    mode = str(pget(params, "NOFLY_THRESHOLD_MODE", "greater_equal")).lower()
    if mode == "greater_equal":
        mask &= slow >= threshold
    elif mode == "greater":
        mask &= slow > threshold
    elif mode == "equal":
        mask &= np.isclose(slow, threshold)
    else:
        raise ValueError(f"Unknown NOFLY_THRESHOLD_MODE: {mode}")
    return mask


def _candidate_row_from_model_index(
    row: pd.Series,
    idx: int,
    model: LoadedModel,
    hit_count: np.ndarray,
) -> dict:
    """Return candidate row values updated to a new model node index."""
    idx = int(idx)
    out = dict(row)
    out["model_index"] = idx
    out["x"] = float(model.xy_original[idx, 0])
    out["y"] = float(model.xy_original[idx, 1])
    out["x_m"] = float(model.xy_metric[idx, 0])
    out["y_m"] = float(model.xy_metric[idx, 1])
    out["z"] = (
        float(model.df[model.z_col].iloc[idx])
        if model.z_col is not None and pd.notna(model.df[model.z_col].iloc[idx])
        else np.nan
    )
    out["slowness"] = (
        float(model.df[model.slowness_col].iloc[idx])
        if model.slowness_col is not None and pd.notna(model.df[model.slowness_col].iloc[idx])
        else np.nan
    )
    out["label"] = str(model.df[model.label_col].iloc[idx]) if model.label_col is not None else ""
    out["label_prefix"] = str(model.df[model.label_prefix_col].iloc[idx]) if model.label_prefix_col is not None else ""
    out["route_hit_count"] = int(hit_count[idx])
    return out


def _distance_to_nofly_nodes_m(model: LoadedModel, nofly_mask: np.ndarray) -> np.ndarray:
    """Return nearest no-fly distance for every model node in metric meters."""
    dist = np.full(len(model.df), np.inf, dtype=float)
    nofly_idx = np.flatnonzero(nofly_mask)
    finite_nodes = _finite_xy_mask(model.xy_metric)
    if len(nofly_idx) == 0:
        return dist
    tree = cKDTree(model.xy_metric[nofly_idx])
    qidx = np.flatnonzero(finite_nodes)
    qdist, _ = tree.query(model.xy_metric[qidx], k=1)
    dist[qidx] = qdist
    return dist


def adjust_candidates_for_nofly_clearance(
    model: LoadedModel,
    params: SimpleNamespace,
    eligible_mask: np.ndarray,
    hit_count: np.ndarray,
    candidates: pd.DataFrame,
) -> pd.DataFrame:
    """Shift traffic-node candidates away from nearby no-fly/obstacle nodes.

    Logic
    -----
    KMeans finds high route-hit-density representatives, but some selected raw
    nodes can sit very close to no-fly/obstacle cells.  For a practical traffic
    node, surrounding free space matters.  This post-processing step checks the
    nearest no-fly distance and, only when a candidate is too close, searches a
    nearby eligible replacement node with better clearance.

    The original node is kept when no better surrounding-space candidate exists.
    """
    if candidates is None or candidates.empty:
        return candidates

    enabled = bool(pget(params, "ENABLE_CANDIDATE_CLEARANCE_SHIFT", True))
    min_clearance_m = float(pget(params, "CANDIDATE_MIN_NOFLY_CLEARANCE_M", 150.0))
    search_radius_m = float(pget(params, "CANDIDATE_SHIFT_SEARCH_RADIUS_M", 600.0))
    min_sep_m = float(pget(params, "CANDIDATE_SHIFT_MIN_SEPARATION_M", pget(params, "CANDIDATE_MIN_SEPARATION_M", 300.0)))
    max_hit_loss_fraction = float(pget(params, "CANDIDATE_SHIFT_MAX_HIT_LOSS_FRACTION", 1.0))
    clearance_weight = float(pget(params, "CANDIDATE_SHIFT_CLEARANCE_WEIGHT", 1.0))
    hit_weight = float(pget(params, "CANDIDATE_SHIFT_HIT_WEIGHT", 0.25))
    distance_penalty = float(pget(params, "CANDIDATE_SHIFT_DISTANCE_PENALTY", 0.20))
    require_clearance_target = bool(pget(params, "CANDIDATE_SHIFT_REQUIRE_CLEARANCE_TARGET", True))
    enforce_separation = bool(pget(params, "CANDIDATE_SHIFT_ENFORCE_CANDIDATE_SEPARATION", True))

    nofly_mask = build_nofly_mask(model, params)
    nofly_clearance = _distance_to_nofly_nodes_m(model, nofly_mask)
    eligible_indices = np.flatnonzero(eligible_mask)

    if len(eligible_indices) == 0 or not np.any(nofly_mask):
        out = candidates.copy()
        out["original_model_index"] = out["model_index"].astype(int)
        out["shifted_from_model_index"] = ""
        out["candidate_shifted"] = False
        out["candidate_shift_distance_m"] = 0.0
        out["original_nofly_clearance_m"] = np.inf
        out["nofly_clearance_m"] = np.inf
        out["shift_reason"] = "no no-fly nodes found"
        return out

    eligible_tree = cKDTree(model.xy_metric[eligible_indices])
    rows = []
    original_indices = candidates["model_index"].astype(int).tolist()
    final_indices: list[int] = []
    shifted_count = 0

    for pos, (_, row) in enumerate(candidates.iterrows()):
        orig_idx = int(row["model_index"])
        orig_clearance = float(nofly_clearance[orig_idx])
        orig_hit = int(hit_count[orig_idx])

        base = dict(row)
        base.setdefault("original_model_index", orig_idx)
        base["original_model_index"] = orig_idx
        base["shifted_from_model_index"] = ""
        base["candidate_shifted"] = False
        base["candidate_shift_distance_m"] = 0.0
        base["original_nofly_clearance_m"] = orig_clearance
        base["nofly_clearance_m"] = orig_clearance
        base["shift_search_candidate_count"] = 0
        base["shift_selected_score"] = np.nan
        base["shift_reason"] = "clearance ok"

        if (not enabled) or (not math.isfinite(orig_clearance)) or orig_clearance >= min_clearance_m:
            rows.append(base)
            final_indices.append(orig_idx)
            continue

        local = eligible_tree.query_ball_point(model.xy_metric[orig_idx], r=search_radius_m)
        if not local:
            base["shift_reason"] = "kept: no eligible nodes inside search radius"
            rows.append(base)
            final_indices.append(orig_idx)
            continue

        cand_idx = eligible_indices[np.asarray(local, dtype=int)]
        cand_idx = cand_idx[cand_idx != orig_idx]
        if len(cand_idx) == 0:
            base["shift_reason"] = "kept: no alternative eligible nodes inside search radius"
            rows.append(base)
            final_indices.append(orig_idx)
            continue

        # Prefer nodes that satisfy the clearance target.  If this is disabled,
        # allow any node that improves clearance.
        if require_clearance_target:
            cand_idx = cand_idx[nofly_clearance[cand_idx] >= min_clearance_m]
        else:
            cand_idx = cand_idx[nofly_clearance[cand_idx] > orig_clearance]

        if len(cand_idx) == 0:
            base["shift_reason"] = "kept: no nearby node improves required no-fly clearance"
            rows.append(base)
            final_indices.append(orig_idx)
            continue

        # Optionally prevent shifting onto another existing/future candidate.
        if enforce_separation and min_sep_m > 0:
            other_indices = list(final_indices) + [int(v) for v in original_indices[pos + 1 :]]
            other_indices = [v for v in other_indices if v != orig_idx]
            if other_indices:
                other_xy = model.xy_metric[np.asarray(other_indices, dtype=int)]
                other_tree = cKDTree(other_xy)
                dist_other, _ = other_tree.query(model.xy_metric[cand_idx], k=1)
                cand_idx = cand_idx[dist_other >= min_sep_m]

        if len(cand_idx) == 0:
            base["shift_reason"] = "kept: clearance alternatives violate candidate separation"
            rows.append(base)
            final_indices.append(orig_idx)
            continue

        # Allow lower traffic density, but optionally reject extreme hit loss.
        # max_hit_loss_fraction=1.0 means allow down to zero hits.
        min_allowed_hit = max(0.0, float(orig_hit) * (1.0 - max(0.0, min(1.0, max_hit_loss_fraction))))
        cand_idx = cand_idx[hit_count[cand_idx] >= min_allowed_hit]
        if len(cand_idx) == 0:
            base["shift_reason"] = "kept: all clearance alternatives lose too much route-hit density"
            rows.append(base)
            final_indices.append(orig_idx)
            continue

        shift_dist = np.linalg.norm(model.xy_metric[cand_idx] - model.xy_metric[orig_idx], axis=1)
        clearance_norm = np.minimum(nofly_clearance[cand_idx] / max(min_clearance_m, 1.0), 2.0) / 2.0
        hit_norm = hit_count[cand_idx].astype(float) / max(float(hit_count[cand_idx].max()), float(orig_hit), 1.0)
        dist_norm = shift_dist / max(search_radius_m, 1.0)
        score = clearance_weight * clearance_norm + hit_weight * hit_norm - distance_penalty * dist_norm

        best_local = int(np.argmax(score))
        new_idx = int(cand_idx[best_local])
        new_clearance = float(nofly_clearance[new_idx])
        new_row = _candidate_row_from_model_index(row, new_idx, model, hit_count)
        new_row["original_model_index"] = orig_idx
        new_row["shifted_from_model_index"] = orig_idx
        new_row["candidate_shifted"] = True
        new_row["candidate_shift_distance_m"] = float(shift_dist[best_local])
        new_row["original_nofly_clearance_m"] = orig_clearance
        new_row["nofly_clearance_m"] = new_clearance
        new_row["shift_search_candidate_count"] = int(len(cand_idx))
        new_row["shift_selected_score"] = float(score[best_local])
        new_row["shift_reason"] = (
            f"shifted: clearance {orig_clearance:.1f} m -> {new_clearance:.1f} m; "
            f"hit {orig_hit} -> {int(hit_count[new_idx])}"
        )
        rows.append(new_row)
        final_indices.append(new_idx)
        shifted_count += 1

    out = pd.DataFrame(rows)
    # Preserve candidate order and IDs after shifting.
    if "candidate_id" in candidates.columns:
        out["candidate_id"] = candidates["candidate_id"].to_numpy()

    close_count = int(np.count_nonzero(out["original_nofly_clearance_m"].to_numpy(dtype=float) < min_clearance_m))
    print(
        "[kmean] Candidate no-fly clearance adjustment: "
        f"checked={len(out)}, close={close_count}, shifted={shifted_count}, "
        f"target_clearance={min_clearance_m:.1f} m"
    )
    if shifted_count > 0:
        cols = [
            "candidate_id",
            "candidate_type",
            "original_model_index",
            "model_index",
            "candidate_shift_distance_m",
            "original_nofly_clearance_m",
            "nofly_clearance_m",
            "route_hit_count",
        ]
        show = [c for c in cols if c in out.columns]
        print(out.loc[out["candidate_shifted"].astype(bool), show].to_string(index=False))
    return out.reset_index(drop=True)


def build_node_output_table(
    model: LoadedModel,
    eligible_mask: np.ndarray,
    hit_count: np.ndarray,
    n_processed_routes: int,
) -> pd.DataFrame:
    df = model.df.copy()
    df["model_index"] = np.arange(len(df), dtype=int)
    df["x_original"] = model.xy_original[:, 0]
    df["y_original"] = model.xy_original[:, 1]
    df["x_m"] = model.xy_metric[:, 0]
    df["y_m"] = model.xy_metric[:, 1]
    df["candidate_eligible"] = eligible_mask
    df["route_hit_count"] = hit_count
    df["route_hit_fraction"] = hit_count / max(float(n_processed_routes), 1.0)
    return df


def build_node_objective_candidate_table(
    model: LoadedModel,
    params: SimpleNamespace,
    eligible_mask: np.ndarray,
    hit_count: np.ndarray,
    n_processed_routes: int,
    candidates: pd.DataFrame,
) -> pd.DataFrame:
    """Build a full node table with objective and TN-candidate flags.

    Output intention
    ----------------
    Save one whole-map table that contains:
        - all raw model nodes
        - objective flags/types (DB, DK, FLZ, RA by default)
        - TN candidate flags/types (major/minor)

    This is useful for later network planning and auditing.
    """
    df = build_node_output_table(model, eligible_mask, hit_count, n_processed_routes)

    label_col = model.label_col
    prefix_col = model.label_prefix_col

    labels = df[label_col].fillna("").astype(str) if label_col in df.columns else pd.Series([""] * len(df))
    prefixes = df[prefix_col].fillna("").astype(str).str.upper() if prefix_col in df.columns else pd.Series([""] * len(df))

    objective_prefixes = {
        str(v).upper()
        for v in _as_list(pget(params, "OBJECTIVE_LABEL_PREFIXES", ["DB", "DK", "FLZ", "RA"]))
    }
    is_objective = prefixes.isin(objective_prefixes)
    df["is_objective"] = is_objective.to_numpy()
    df["objective_label"] = np.where(is_objective.to_numpy(), labels.to_numpy(dtype=object), "")
    df["objective_prefix"] = np.where(is_objective.to_numpy(), prefixes.to_numpy(dtype=object), "")

    if candidates is None or candidates.empty:
        df["is_candidate"] = False
        df["candidate_id"] = ""
        df["candidate_type"] = ""
        df["candidate_route_hit_count"] = np.nan
        return df

    # Keep useful candidate condition/shift fields in the merged whole-map table.
    preferred_cols = [
        "model_index",
        "candidate_id",
        "candidate_type",
        "route_hit_count",
        "original_model_index",
        "shifted_from_model_index",
        "candidate_shifted",
        "candidate_shift_distance_m",
        "original_nofly_clearance_m",
        "nofly_clearance_m",
        "shift_reason",
    ]
    cand_cols = [c for c in preferred_cols if c in candidates.columns]
    cand_df = candidates[cand_cols].copy()
    if "route_hit_count" in cand_df.columns:
        cand_df = cand_df.rename(columns={"route_hit_count": "candidate_route_hit_count"})
    df = df.merge(cand_df, on="model_index", how="left")
    df["is_candidate"] = df["candidate_id"].notna()
    df["candidate_id"] = df["candidate_id"].fillna("")
    df["candidate_type"] = df["candidate_type"].fillna("")
    if "candidate_shifted" in df.columns:
        df["candidate_shifted"] = df["candidate_shifted"].fillna(False)
    return df


def _routes_to_table(routes: list[LoadedRoute]) -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "route_file": str(r.path),
                "route_name": r.path.name,
                "route_key": r.route_key,
                "source_kind": r.source_kind,
                "status": r.status,
                "reason": r.reason,
                "n_raw_points": r.n_raw_points,
                "n_dense_points": r.n_dense_points,
                "hit_nodes": r.hit_nodes,
            }
            for r in routes
        ]
    )


def _plot_xy(use_original: bool, model: LoadedModel, xy_metric: np.ndarray | None = None) -> tuple[np.ndarray, str, str]:
    if use_original:
        return model.xy_original, model.x_col, model.y_col
    if xy_metric is None:
        xy_metric = model.xy_metric
    return xy_metric, "x_m", "y_m"


def _overlay_kmean_candidates(ax, candidates: pd.DataFrame, params: SimpleNamespace, use_original: bool) -> None:
    """Overlay KMeans major/minor candidates with the same symbol logic as Figure 02."""
    if candidates is None or candidates.empty:
        return

    plot_major_candidates = bool(pget(params, "PLOT_KMEAN_MAJOR_CANDIDATES", True))
    plot_minor_candidates = bool(pget(params, "PLOT_KMEAN_MINOR_CANDIDATES", True))
    plot_candidate_labels = bool(pget(params, "PLOT_KMEAN_CANDIDATE_LABELS", True))
    plot_major_labels = bool(pget(params, "PLOT_KMEAN_MAJOR_LABELS", True))
    plot_minor_labels = bool(pget(params, "PLOT_KMEAN_MINOR_LABELS", True))
    label_field = str(pget(params, "PLOT_KMEAN_CANDIDATE_LABEL_FIELD", "candidate_id"))
    label_fontsize = float(pget(params, "PLOT_KMEAN_CANDIDATE_LABEL_FONTSIZE", 7.0))
    label_dx = float(pget(params, "PLOT_KMEAN_CANDIDATE_LABEL_DX", 0.0))
    label_dy = float(pget(params, "PLOT_KMEAN_CANDIDATE_LABEL_DY", 0.0))

    major = candidates["candidate_type"].astype(str).str.lower() == "major"
    minor = candidates["candidate_type"].astype(str).str.lower() == "minor"
    cx = candidates["x"].to_numpy() if use_original else candidates["x_m"].to_numpy()
    cy = candidates["y"].to_numpy() if use_original else candidates["y_m"].to_numpy()

    if plot_major_candidates and major.any():
        ax.scatter(
            cx[major.to_numpy()],
            cy[major.to_numpy()],
            s=float(pget(params, "PLOT_CANDIDATE_SIZE_MAJOR", 110)),
            marker=str(pget(params, "PLOT_CANDIDATE_MARKER_MAJOR", "*")),
            c=str(pget(params, "PLOT_CANDIDATE_COLOR_MAJOR", "red")),
            edgecolors=str(pget(params, "PLOT_CANDIDATE_EDGE_COLOR", "white")),
            linewidths=float(pget(params, "PLOT_CANDIDATE_EDGE_WIDTH", 0.6)),
            label="KMeans major candidates",
            zorder=6,
        )

    if plot_minor_candidates and minor.any():
        ax.scatter(
            cx[minor.to_numpy()],
            cy[minor.to_numpy()],
            s=float(pget(params, "PLOT_CANDIDATE_SIZE_MINOR", 70)),
            marker=str(pget(params, "PLOT_CANDIDATE_MARKER_MINOR", "o")),
            c=str(pget(params, "PLOT_CANDIDATE_COLOR_MINOR", "deepskyblue")),
            edgecolors=str(pget(params, "PLOT_CANDIDATE_EDGE_COLOR", "white")),
            linewidths=float(pget(params, "PLOT_CANDIDATE_EDGE_WIDTH", 0.5)),
            label="KMeans minor candidates",
            zorder=5,
        )

    if plot_candidate_labels:
        for _, row in candidates.iterrows():
            ctype = str(row.get("candidate_type", "")).lower()
            if ctype == "major" and (not plot_major_candidates or not plot_major_labels):
                continue
            if ctype == "minor" and (not plot_minor_candidates or not plot_minor_labels):
                continue

            px = float(row["x"] if use_original else row["x_m"])
            py = float(row["y"] if use_original else row["y_m"])

            if label_field == "candidate_id_hit":
                label_text = f"{row.get('candidate_id', '')} ({int(row.get('route_hit_count', 0))})"
            elif label_field == "hit_count":
                label_text = str(int(row.get("route_hit_count", 0)))
            elif label_field in row.index:
                label_text = str(row[label_field])
            else:
                label_text = str(row.get("candidate_id", ""))

            ax.text(
                px + label_dx,
                py + label_dy,
                label_text,
                fontsize=label_fontsize,
                ha=str(pget(params, "PLOT_KMEAN_CANDIDATE_LABEL_HA", "left")),
                va=str(pget(params, "PLOT_KMEAN_CANDIDATE_LABEL_VA", "bottom")),
                zorder=7,
            )



def _mask_long_triangles(triangulation, xy_metric: np.ndarray, max_edge_m: float) -> np.ndarray | None:
    """Return a triangle mask where any edge is longer than max_edge_m."""
    if max_edge_m <= 0:
        return None
    triangles = triangulation.triangles
    pts = xy_metric[triangles]
    e01 = np.linalg.norm(pts[:, 0, :] - pts[:, 1, :], axis=1)
    e12 = np.linalg.norm(pts[:, 1, :] - pts[:, 2, :], axis=1)
    e20 = np.linalg.norm(pts[:, 2, :] - pts[:, 0, :], axis=1)
    return (e01 > max_edge_m) | (e12 > max_edge_m) | (e20 > max_edge_m)


def _make_traffic_density_mesh_figure(
    model: LoadedModel,
    params: SimpleNamespace,
    fig_dir: Path,
    dpi: int,
    use_original: bool,
    eligible_mask: np.ndarray,
    hit_count: np.ndarray,
    processed_routes: list[LoadedRoute],
) -> None:
    """
    Figure 00: mesh-style traffic-density map.

    The mesh is built from the raw model nodes and colored by route-hit count.
    Triangle masking is computed in metric coordinates, so it also works when
    the plotted axes are lon/lat degrees.
    """
    if not bool(pget(params, "MAKE_TRAFFIC_DENSITY_MESH_FIGURE", True)):
        return

    import matplotlib.pyplot as plt
    import matplotlib.tri as mtri

    only_positive = bool(pget(params, "TRAFFIC_DENSITY_MESH_ONLY_HIT_POSITIVE", False))
    mesh_mask = eligible_mask.copy()
    if only_positive:
        mesh_mask &= hit_count > 0

    idx = np.flatnonzero(mesh_mask)
    if idx.size < 3:
        print("[kmean] Skip 00_trafic_density.png: fewer than 3 mesh nodes.")
        return

    xy_plot_all, xlab, ylab = _plot_xy(use_original, model)
    x_plot = xy_plot_all[idx, 0]
    y_plot = xy_plot_all[idx, 1]
    xy_metric = model.xy_metric[idx]
    z = hit_count[idx].astype(float)

    finite = np.isfinite(x_plot) & np.isfinite(y_plot) & np.isfinite(z)
    x_plot = x_plot[finite]
    y_plot = y_plot[finite]
    xy_metric = xy_metric[finite]
    z = z[finite]
    if len(z) < 3:
        print("[kmean] Skip 00_trafic_density.png: fewer than 3 finite mesh nodes.")
        return

    triang = mtri.Triangulation(x_plot, y_plot)
    max_edge_m = float(pget(params, "TRAFFIC_DENSITY_MESH_MAX_EDGE_M", 900.0))
    long_mask = _mask_long_triangles(triang, xy_metric, max_edge_m)
    if long_mask is not None:
        triang.set_mask(long_mask)

    fig, ax = plt.subplots(figsize=(10, 8))
    cmap = str(pget(params, "TRAFFIC_DENSITY_MESH_CMAP", "inferno"))
    shading = str(pget(params, "TRAFFIC_DENSITY_MESH_SHADING", "gouraud")).lower()
    if shading not in {"flat", "gouraud"}:
        shading = "gouraud"

    # tripcolor gives a real triangular mesh map; the color value is route-hit count.
    mesh = ax.tripcolor(triang, z, shading=shading, cmap=cmap)
    cb = fig.colorbar(mesh, ax=ax, shrink=0.82, pad=0.02)
    cb.set_label("Traffic density / route hit count")

    if bool(pget(params, "PLOT_ROUTE_LINES_ON_TRAFFIC_MESH", True)):
        max_routes = int(pget(params, "PLOT_MAX_ROUTES", 300))
        for r in processed_routes[:max_routes]:
            rxy = r.xy_original if use_original else r.xy_metric
            if len(rxy) >= 2:
                ax.plot(rxy[:, 0], rxy[:, 1], lw=0.45, alpha=0.20, color="white")

    if bool(pget(params, "PLOT_TRAFFIC_MESH_NODE_DOTS", False)):
        ax.scatter(
            x_plot,
            y_plot,
            s=float(pget(params, "TRAFFIC_MESH_NODE_DOT_SIZE", 2.0)),
            c="black",
            alpha=0.18,
            linewidths=0,
        )

    if bool(pget(params, "PLOT_TRAFFIC_MESH_EXCLUDED_NODES", False)):
        excluded = ~eligible_mask
        xy_ex = xy_plot_all[excluded]
        if len(xy_ex) > 0:
            ax.scatter(xy_ex[:, 0], xy_ex[:, 1], s=2.0, c="black", alpha=0.08, linewidths=0)

    ax.set_title("Traffic-density mesh from Theta* route hit-counts")
    ax.set_xlabel(xlab)
    ax.set_ylabel(ylab)
    ax.set_aspect("equal", adjustable="box")
    fig.tight_layout()
    out_file = fig_dir / "00_trafic_density.png"
    fig.savefig(out_file, dpi=dpi)
    plt.close(fig)
    print(f"[kmean] Saved: {out_file}")

def make_figures(
    model: LoadedModel,
    params: SimpleNamespace,
    output_dir: Path,
    eligible_mask: np.ndarray,
    hit_count: np.ndarray,
    candidates: pd.DataFrame,
    processed_routes: list[LoadedRoute],
) -> None:
    if not bool(pget(params, "MAKE_FIGURES", True)):
        return

    import matplotlib.pyplot as plt

    fig_dir = output_dir / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)
    dpi = int(pget(params, "FIGURE_DPI", 220))
    node_size = float(pget(params, "PLOT_NODE_SIZE", 8))
    use_original = bool(pget(params, "PLOT_USE_ORIGINAL_XY", True))
    xy_plot, xlab, ylab = _plot_xy(use_original, model)

    # Figure 00: mesh-style traffic-density map.
    _make_traffic_density_mesh_figure(
        model=model,
        params=params,
        fig_dir=fig_dir,
        dpi=dpi,
        use_original=use_original,
        eligible_mask=eligible_mask,
        hit_count=hit_count,
        processed_routes=processed_routes,
    )

    # Figure 01: route hit density map.
    fig, ax = plt.subplots(figsize=(10, 8))
    excluded = ~eligible_mask
    if excluded.any():
        ax.scatter(xy_plot[excluded, 0], xy_plot[excluded, 1], s=node_size, c="black", alpha=0.18, linewidths=0, label="excluded/no-fly/objective")
    sc = ax.scatter(
        xy_plot[eligible_mask, 0],
        xy_plot[eligible_mask, 1],
        c=hit_count[eligible_mask],
        s=node_size,
        cmap="inferno",
        linewidths=0,
        label="eligible model nodes",
    )
    cb = fig.colorbar(sc, ax=ax, shrink=0.82, pad=0.02)
    cb.set_label("Route hit count")
    ax.set_title("Route hit-density on raw model nodes")
    ax.set_xlabel(xlab)
    ax.set_ylabel(ylab)
    ax.set_aspect("equal", adjustable="box")
    ax.legend(loc="upper right", frameon=True)
    fig.tight_layout()
    out_file = fig_dir / "01_route_hit_density.png"
    fig.savefig(out_file, dpi=dpi)
    print(f"[kmean] Saved: {out_file}")
    plt.close(fig)

    # Figure 02: KMeans candidates over hit density and route lines.
    fig, ax = plt.subplots(figsize=(10, 8))
    ax.scatter(xy_plot[eligible_mask, 0], xy_plot[eligible_mask, 1], c=hit_count[eligible_mask], s=node_size, cmap="Greys", linewidths=0, alpha=0.55)

    if bool(pget(params, "PLOT_ROUTE_LINES", True)):
        max_routes = int(pget(params, "PLOT_MAX_ROUTES", 300))
        for r in processed_routes[:max_routes]:
            rxy = r.xy_original if use_original else r.xy_metric
            if len(rxy) >= 2:
                ax.plot(rxy[:, 0], rxy[:, 1], lw=0.5, alpha=0.25)

    _overlay_kmean_candidates(ax, candidates, params, use_original)

    ax.set_title("KMeans traffic-node candidates from route hit-density")
    ax.set_xlabel(xlab)
    ax.set_ylabel(ylab)
    ax.set_aspect("equal", adjustable="box")
    ax.legend(loc="upper right", frameon=True)
    fig.tight_layout()
    out_file = fig_dir / "02_kmean_major_minor_candidates.png"
    fig.savefig(out_file, dpi=dpi)
    print(f"[kmean] Saved: {out_file}")
    plt.close(fig)

    # Figure 03: histogram of route-hit counts.
    fig, ax = plt.subplots(figsize=(9, 5))
    positive_hits = hit_count[eligible_mask]
    positive_hits = positive_hits[np.isfinite(positive_hits)]
    bins = max(10, min(60, int(np.nanmax(positive_hits)) + 1 if positive_hits.size else 10))
    ax.hist(positive_hits, bins=bins)
    ax.set_title("Distribution of route hit counts on eligible nodes")
    ax.set_xlabel("Route hit count")
    ax.set_ylabel("Number of model nodes")
    fig.tight_layout()
    out_file = fig_dir / "03_hit_count_histogram.png"
    fig.savefig(out_file, dpi=dpi)
    print(f"[kmean] Saved: {out_file}")
    plt.close(fig)

    # Figure 04: mesh traffic density with no-fly overlay and KMeans candidates.
    if bool(pget(params, "MAKE_TRAFFIC_DENSITY_CANDIDATES_FIGURE", True)):
        import matplotlib.tri as mtri

        only_positive = bool(pget(params, "TRAFFIC_DENSITY_CANDIDATES_ONLY_HIT_POSITIVE", False))
        mesh_mask = eligible_mask.copy()
        if only_positive:
            mesh_mask &= hit_count > 0

        idx = np.flatnonzero(mesh_mask)
        if idx.size < 3:
            print("[kmean] Skip 04_trafic_density_candidates.png: fewer than 3 mesh nodes.")
        else:
            x_plot = xy_plot[idx, 0]
            y_plot = xy_plot[idx, 1]
            xy_metric = model.xy_metric[idx]
            z = hit_count[idx].astype(float)

            finite = np.isfinite(x_plot) & np.isfinite(y_plot) & np.isfinite(z)
            x_plot = x_plot[finite]
            y_plot = y_plot[finite]
            xy_metric = xy_metric[finite]
            z = z[finite]

            if len(z) < 3:
                print("[kmean] Skip 04_trafic_density_candidates.png: fewer than 3 finite mesh nodes.")
            else:
                triang = mtri.Triangulation(x_plot, y_plot)
                max_edge_m = float(pget(params, "TRAFFIC_DENSITY_CANDIDATES_MAX_EDGE_M", pget(params, "TRAFFIC_DENSITY_MESH_MAX_EDGE_M", 900.0)))
                long_mask = _mask_long_triangles(triang, xy_metric, max_edge_m)
                if long_mask is not None:
                    triang.set_mask(long_mask)

                fig, ax = plt.subplots(figsize=(10, 8))
                cmap = str(pget(params, "TRAFFIC_DENSITY_CANDIDATES_CMAP", pget(params, "TRAFFIC_DENSITY_MESH_CMAP", "inferno")))
                shading = str(pget(params, "TRAFFIC_DENSITY_CANDIDATES_SHADING", pget(params, "TRAFFIC_DENSITY_MESH_SHADING", "gouraud"))).lower()
                if shading not in {"flat", "gouraud"}:
                    shading = "gouraud"

                mesh = ax.tripcolor(triang, z, shading=shading, cmap=cmap)
                cb = fig.colorbar(mesh, ax=ax, shrink=0.82, pad=0.02)
                cb.set_label("Traffic density / route hit count")

                if bool(pget(params, "PLOT_ROUTE_LINES_ON_TRAFFIC_DENSITY_CANDIDATES", False)):
                    max_routes = int(pget(params, "PLOT_MAX_ROUTES", 300))
                    for r in processed_routes[:max_routes]:
                        rxy = r.xy_original if use_original else r.xy_metric
                        if len(rxy) >= 2:
                            ax.plot(rxy[:, 0], rxy[:, 1], lw=0.45, alpha=0.18, color="white")

                if bool(pget(params, "PLOT_NOFLY_OVERLAY_ON_TRAFFIC_DENSITY_CANDIDATES", True)):
                    nofly_mask = build_nofly_mask(model, params)
                    xy_nofly = xy_plot[nofly_mask]
                    if len(xy_nofly) > 0:
                        ax.scatter(
                            xy_nofly[:, 0],
                            xy_nofly[:, 1],
                            s=float(pget(params, "NOFLY_OVERLAY_SIZE", 8.0)),
                            marker=str(pget(params, "NOFLY_OVERLAY_MARKER", "s")),
                            c=str(pget(params, "NOFLY_OVERLAY_COLOR", "black")),
                            alpha=float(pget(params, "NOFLY_OVERLAY_ALPHA", 0.40)),
                            linewidths=0,
                            label="no-fly zone",
                            zorder=4,
                        )

                _overlay_kmean_candidates(ax, candidates, params, use_original)
                ax.set_title("Traffic-density mesh with no-fly overlay and KMeans candidates")
                ax.set_xlabel(xlab)
                ax.set_ylabel(ylab)
                ax.set_aspect("equal", adjustable="box")
                ax.legend(loc="upper right", frameon=True)
                fig.tight_layout()
                out_file = fig_dir / "04_trafic_density_candidates.png"
                fig.savefig(out_file, dpi=dpi)
                print(f"[kmean] Saved: {out_file}")
                plt.close(fig)


def save_outputs(
    model: LoadedModel,
    params: SimpleNamespace,
    output_dir: Path,
    eligible_mask: np.ndarray,
    hit_count: np.ndarray,
    candidates: pd.DataFrame,
    processed_routes: list[LoadedRoute],
    skipped_routes: list[LoadedRoute],
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    _write_params_snapshot(params, output_dir)

    if bool(pget(params, "SAVE_NODE_HIT_TABLE", True)):
        node_table = build_node_output_table(model, eligible_mask, hit_count, len(processed_routes))
        node_table.to_csv(output_dir / "all_model_nodes_route_hit_density.csv", index=False)

    if bool(pget(params, "SAVE_NODE_OBJECTIVE_CANDIDATE_TABLE", True)):
        node_obj_cand = build_node_objective_candidate_table(
            model=model,
            params=params,
            eligible_mask=eligible_mask,
            hit_count=hit_count,
            n_processed_routes=len(processed_routes),
            candidates=candidates,
        )
        node_obj_cand.to_csv(output_dir / "all_model_nodes_objective_TNcandidates.csv", index=False)

    if bool(pget(params, "SAVE_CANDIDATE_TABLE", True)):
        candidates.to_csv(output_dir / "traffic_node_candidates_major_minor.csv", index=False)

    if bool(pget(params, "SAVE_ROUTE_SUMMARY_TABLE", True)):
        route_summary = pd.concat([
            _routes_to_table(processed_routes),
            _routes_to_table(skipped_routes),
        ], ignore_index=True)
        route_summary.to_csv(output_dir / "route_file_processing_summary.csv", index=False)

    make_figures(model, params, output_dir, eligible_mask, hit_count, candidates, processed_routes)


# ----------------------------------------------------------------------
# Main workflow
# ----------------------------------------------------------------------


def run_route_hit_density_kmeans(params: SimpleNamespace) -> pd.DataFrame:
    output_dir = Path(pget(params, "OUTPUT_DIR", "output/04_kmean_route_hit_density"))
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"[kmean] src.kmean module version: {MODULE_VERSION}")
    print("[kmean] Loading raw model nodes...")
    model = load_model(params)
    print(f"[kmean] Model nodes: {len(model.df):,}")
    print(f"[kmean] Coordinate mode: {model.metric_mode}")

    print("[kmean] Building candidate eligibility mask...")
    eligible_mask = build_eligible_mask(model, params)
    print(f"[kmean] Eligible candidate nodes: {int(eligible_mask.sum()):,}")

    print("[kmean] Counting route hits around model nodes...")
    hit_count, processed_routes, skipped_routes = compute_route_hits(model, params, eligible_mask)
    print(f"[kmean] Processed route files: {len(processed_routes):,}")
    print(f"[kmean] Skipped route files: {len(skipped_routes):,}")
    if skipped_routes:
        print("[kmean] First skipped route files / reasons:")
        for r in skipped_routes[:10]:
            print(f"[kmean]   skipped {r.path.name}: {r.reason}")
    print(f"[kmean] Max route-hit count: {int(hit_count.max())}")

    print("[kmean] Running KMeans for major/minor traffic candidates...")
    candidates = select_candidates(model, params, eligible_mask, hit_count)

    print("[kmean] Checking candidate clearance from no-fly/obstacle nodes...")
    candidates = adjust_candidates_for_nofly_clearance(model, params, eligible_mask, hit_count, candidates)

    print(f"[kmean] Selected traffic-node candidates: {len(candidates):,}")
    if not candidates.empty:
        cols = ["candidate_id", "candidate_type", "model_index", "x", "y", "route_hit_count", "nofly_clearance_m", "candidate_shifted"]
        cols = [c for c in cols if c in candidates.columns]
        print(candidates[cols].to_string(index=False))

    print("[kmean] Saving outputs...")
    save_outputs(model, params, output_dir, eligible_mask, hit_count, candidates, processed_routes, skipped_routes)
    print(f"[kmean] Done. Output directory: {output_dir}")
    return candidates
